version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-cli
    versions:
    - 3.24.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.1.0
    - 7.2.0
